steps:
  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-transkun-app', '.']

  # Step to push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-transkun-app']

  # Step to deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-transkun-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-transkun-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast2'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'

images:
  - 'gcr.io/$PROJECT_ID/flask-transkun-app'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
